---
slug: rhythm-of-flood-occurrences
title: 'Hydrology basics, episode 2: the rhythm of flood occurrences'
thumbnail_title: 'Hydrology basics, episode 2'
thumbnail_subtitle: 'The rhythm of flood occurrences'
thumbnail_vid: https://player.vimeo.com/video/653714131
author: Ben
date: '2022-11-04'
categories: [Hydrology basics]
tags: [sonification,animation,statistics,floods]
toc: yes
autoCollapseToc: yes
---

"*This was a 100-year event*". 

This type of sentence is often heard [in the news](https://www.smh.com.au/national/mid-north-coast-enduring-one-in-100-year-event-20210321-p57cny.html) after a flood or a storm hits somewhere, as it does a good job at carrying the rarity of what happened. But beyond the catchy expression hides a genuine risk management concept called [**return period**](https://en.wikipedia.org/wiki/Return_period), that is as tricky as it is widely used. The aim of this post is to build some intuition around return periods using music (and a tiny bit of math).

# What is a return period?

The return period is defined as the **average** duration between two successive occurences of an event. So a flood has a return period of e.g. 10 years if, **on average**, you would expect to wait 10 years until something as bad (or even worse!) happens again. Importantly, there is [no periodicity](https://theconversation.com/what-is-a-1-in-100-year-weather-event-and-why-do-they-keep-happening-so-often-157589) in the occurrence of 10-year events: you may wait 2 years, then 8 years, then 20 years etc. between two successive 10-year floods, and only in the longer-term will these durations average to 10 years.

The 'return period' terminology is hence confusing because of the unfortunate use of the word 'period'. The expression [recurrence interval](https://www.usgs.gov/special-topics/water-science-school/science/100-year-flood) is in fact often considered as a better alternative. Moreover, the following definition is also frequently used: a flood is qualified as a 10-year event if the probability of something as bad happening in any given year is 1/10. This is arguably a better alternative since the use of a probability makes the random nature of flood occurrences more explicit. But it also raises a legitimate question: why is this definition equivalent to the previous one? How do you move from a probability (1/10) to an average duration (10 years)? 

# The rhythm of flood occurrences 

The video below explores this issue by [sonifying](/blog/sonification-sequencing) the occurrence of floods and listening to the corresponding rhythm. At the beginning, the video illustrates the rhythm induced by an event occuring every 10 years exactly. It then switches to random flood occurrences: every time the flood time series on the right exceeds a threshold, a bass sound is triggered. This threshold has been computed so that it has a probability of being exceeded equal to 1/10. The graphic building up during the video aims at keeping track of the duration between two successive events: if the definitions discussed above are equivalent, these durations should average to 10 years in the longer term.

<p></p>

<iframe src="https://player.vimeo.com/video/653714131" frameborder="0" width="100%" height="440" allowfullscreen="allowfullscreen"></iframe>

<p></p>

This video highlighths the highly irregular nature of flood occurrences: the steady rhythm of the intro switches to a much shakyer and unpredictable rhythm, reflecting the randomness of flood occurrences. 

Inspecting the waiting times between successive events reveals other interesting aspects of how 10-year floods occur. Starting with the good news, the waiting times average to 10 years in the long term as expected (10.3 by the end of the video - close enough!). However, waiting times are not distributed evenly around this average value of 10 years as one may have expected. Instead, the distribution of waiting times is highly **asymetric**, with small values being much more common than large ones: the probability of waiting less than 10 years between two occurrences is roughly 2/3. The *median* waiting time is 6 years, i.e. you have 50% chance of waiting less than 6 years between two successive 10-year floods. So in a nutshell, a sequence of 10-year floods will tend to look like this: several close occurrences (making you feel they are too frequent) and, from time to time, a very long time with no floods (making you forget they even exist!). This has consequences on the perception of flood risk. 

# Let's do the maths

It is actually fairly easy to work out the maths hiding behind this video. Let's assume there was a 10-year flood last year, and let's count the number of years before we see another one (or worse).

* Waiting only one year means that the flood occurs on the first year, and as explained above this has probability 0.1.
* Waiting 2 years means that there is no occurrence on year 1 (this has probability 0.9), but there is one on year 2 (probability 0.1). The probability of having this particular sequence (no occurrence, then occurrence) is 0.9\*0.1=0.09. 
* Waiting 3 years means that there is no occurrence on year 1 (probability 0.9), no occurrence on year 2 (probability 0.9) but there is one on year 3 (probability 0.1). This gives 0.9\*0.9\*0.1=0.9<sup>2</sup>\*0.1=0.081.
* An so one and so forth... waiting 4 years gives 0.9<sup>3</sup>\*0.1, waiting *k* years gives 0.9<sup>*k*-1</sup>\*0.1

This is known as the [geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution) associated with a probability of occurrence *p*=0.1, and [it can be shown](https://en.wikipedia.org/wiki/Geometric_distribution#Moments_and_cumulants) that the mean of this distribution is equal to 1/*p*: this explains the link between a probability of occurrence and an average duration.

# So, return periods or probabilities?

The notion of return period is widely used in the management of natural hazards. The historical reasons why it has become so prevalent are unclear to me. Maybe durations were considered to be more intuitive to handle than probabilities? But this post illustrates that this is not quite the case: return periods are tricky to manipulate and can lead to counter-intuitive results. Some people are even arguing that the concept should be [ditched](https://fivethirtyeight.com/features/its-time-to-ditch-the-concept-of-100-year-floods/) altogether. Whether or not you agree with this statement, one thing is clear: thinking in terms of probability rather than return period is necessary to make computations such as the ones discussed earlier. 

In a future post, we will further explore other apparent oddities of extreme events, such as: why are rare events happenning [so frequently](https://globxblog.shinyapps.io/worldFloods)?

---

**Author**: Ben  

**Codes and data**: browse on [GitHub](https://github.com/globXblog/scripts/tree/main/src/rhythm-of-flood-occurrences)

---


