---
slug: hegs
title: 'Floods and Heavy Precipitation in the World'
thumbnail_title: 'Hydro-Extremes in the World'
thumbnail_subtitle: 'Listen to 100 years of 100-year events'
thumbnail_vid: https://player.vimeo.com/video/802751683
author: Ben
date: '2023-07-17'
categories: [Exploring Data]
tags: [sonification,animation,floods,heavy precipitation]
toc: yes
autoCollapseToc: yes
---

Observed data are essential to understand, quantify and predict the risk posed by extreme climatic events. In the case of floods or heavy precipitation, such data take the form of long series measured at [stream gauging](https://en.wikipedia.org/wiki/Stream_gauge) or [weather](https://en.wikipedia.org/wiki/Weather_station) stations. The longest series may contain more than 100 years of data, but most series are shorter (typically around 50-year long) and moreover data availability strongly varies between the different regions of the world.

We recently published a [paper](https://doi.org/10.1029/2022JD037908) that uses such long series to look into the long-term evolution of hydrologic extremes in the world. The video below illustrates the [flood](https://doi.pangaea.de/10.1594/PANGAEA.887470) and [precipitation](https://www.climdex.org/learn/datasets) datasets used in this paper. As time passes, available stations light up or dim down, with the total number of active stations in the world being tracked by the bottom chart and also by the musical intensity. When a station records a [100-year event](/blog/rhythm-of-flood-occurrences), a large yellow dot pops out and a percussive sound is played. The first half of the video is devoted to floods, the second half to heavy precipitation.

<p></p>

<iframe src="https://player.vimeo.com/video/802751683" frameborder="0" width="100%" height="440" allowfullscreen="allowfullscreen"></iframe>

<p></p>

# Rare events happen frequently

The first striking observation from this video is that 100-year events happen all the time! This might seem surprising at first sight but it is simply due to the fact that what is considered as 'rare' locally becomes in fact quite common when zooming out to a larger scale. As an illustration, the probability that *you* win the national lottery next week is near-zero, but the probability that *someone* wins it is quite high.

Another key observation is that during the 100 years covered by this video, data availability has strongly increased during the first decades before reaching a plateau by the late 60's. It is important to account for this pattern before drawing conclusions on the evolution of hydrologic extremes. Indeed, the first reason why the frequency of 100-year events seems to increase at the beginning of the video is because more and more stations are available to catch them! In the [paper](https://doi.org/10.1029/2022JD037908) mentioned at the beginning of this post, we applied a new method that enables using all available data while properly accounting for the strongly varying data availability. In a nutshell, we found that increasing trends affecting many parts of the world could be detected for heavy precipitation, whereas flood trends appeared weaker and much less consistent. 

These results confirm and extend some of the broad findings summarized by the [IPCC](https://www.ipcc.ch/) (click [here](https://interactive-atlas.ipcc.ch/regional-synthesis#eyJ0eXBlIjoiQ0lEIiwic2VsZWN0ZWRJbmRleCI6InJpdmVyX2Zsb29kIiwic2VsZWN0ZWRWYXJpYWJsZSI6InRyZW5kIiwic2VsZWN0ZWRDb3VudHJ5IjoiR0lDIiwibW9kZSI6Ik1BUCIsImNvbW1vbnMiOnsibGF0Ijo5NzcyLCJsbmciOjQwMDY5Miwiem9vbSI6NCwicHJvaiI6IkVQU0c6NTQwMzAiLCJtb2RlIjoiY29tcGxldGVfYXRsYXMifX0=) for an interactive exploration). The discrepancy between the increasing signal found for heavy precipitation and the lack thereof for floods may appear surprising at first sight, but it can be [explained](https://doi.org/10.1029/2018WR023749) by the diversity and the complexity of [flood-generating mechanisms](/blog/hydrology-basics-1). For instance, flooding in many rivers of the world is generated by snowmelt, not heavy precipitation. In large river catchments, flooding is often caused by long and widespread rainfall rather than localized and short-lived heavy precipitation events. [Some authors](https://doi.org/10.1080/00186368.2021.1912971) have also highlighted that heavier precipitation falling on drier catchments may result in decreasing floods. In summary, while the climate warming signal is by now crystal-clear, and its effect toward increasing heavy precipitation can also be detected, the consequences in terms of river flooding will likely strongly vary across geographical regions and catchment sizes.

---

**Author**: Ben

**Codes and data**: browse on [GitHub](https://github.com/globXblog/scripts/tree/main/src/hegs)

---
